### ISSUE TITLE
Attribution & license

### ISSUE THREAD

**Issue by brentvatne** [arnnis/react-native-match-media-polyfill#3]
Hi there! You should mention in your README that this is a fork of `@expo/match-media` :) Also, it's necessary to add https://github.com/expo/match-media/blob/master/LICENSE to your LICENSE.

**Comment by arnnis** [comment]
Hi, Sure
Actually there is another project with very similar codebase and it is older. so I was not sure I should include which one, or maybe both? I think you need to add that repo to your repo too.
https://github.com/tuckerconnelly/react-native-match-media/
